services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
    environment:
      - PORT=8080
      - MIGRATIONS_DIR=/app/db/migrations

  mmock:
    image: jordimartin/mmock
    volumes:
      - "./test/mocks:/config"
    command:
      - -server-statistics=false
    ports:
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
